### ISSUE TITLE
READE.me: npm install; npm run dev

### ISSUE THREAD

**Issue by zoosky** [liip/bund_ds#103]
A clean checkout of this project does not work.
- npm install  #fails
- npm install --legacy-peer-deps #more successful
- npm run dev # errors

Please update the README.md acoording to the best practice.

Please specify minimal required dependencies, i.e. node version

**Comment by satefan** [comment]
Please also include instructions for css building in the readme

**Comment by sylvainaerni** [comment]
Issue will be handled in https://github.com/swiss/styleguide2021/issues/347
