### ISSUE TITLE
Scroll to Top button doesn't work as expected on mobile Safari

### ISSUE THREAD

**Issue by shvlv** [liip/bund_ds#132]
Hi, thanks for the useful components and Storybook!

Unfortunately, in our tests Scroll to Top button doesn't work as expected on the mobile Safari browser:
1. Clicking by button produces nothing.
2. With top address bar button seems cut. 

There is a screencast from https://storybook.bund-ds.bedev.liip.ch/iframe.html?id=pages-homepage--example&viewMode=story page. Browser data:
```
OS iOS, v16.4
Browser Safari
Screen Size 6.1 in - 5.24 x 2.56 in
Resolution 1170 x 2532 px
Viewport 390 x 664 px
Aspect Ratio 19.5 : 9
```

[safari-scroll-to-top.webm](https://github.com/liip/bund_ds/assets/3157352/0be2c4f6-f8cb-4a05-a035-310e4963fa57)

**Comment by tyrann0us** [comment]
Friendly ping @sylvainaerni, @daviddarx 🙂 
(There's no `CONTRIBUTING.md`, so I pinged the top 2 contributors according to https://github.com/liip/bund_ds/graphs/contributors.)

**Comment by sylvainaerni** [comment]
Hello, 
FYI. This repository is not maintained anymore and handled by another team.
The new repository (https://github.com/swiss/designsystem) is now private.
Please contact <a href="mailto:Davy.Augier@bk.admin.ch">Davy.Augier@bk.admin.ch</a> to request an access.

**Comment by tyrann0us** [comment]
Hi @sylvainaerni, thanks for getting back to us. It might make sense to archive this repo to communicate its state more clearly.

@DavyAugier, I dropped you an email asking for access for our colleagues. Thanks!

**Comment by sylvainaerni** [comment]
Will do, thank you for your patience
