### ISSUE TITLE
Question : is it planned to publish this as a full-fledged NPM package?

### ISSUE THREAD

**Issue by pakb** [liip/bund_ds#133]
Hello,
Is it a goal, in the end, to have this available on [npmjs.com](https://www.npmjs.com/) ?

This way we could `npm install --save-dev bund_ds`, and then in our main Webpack/Vite entry have
```main.js
// main.js
import 'bund_ds/main.css'
```
To have it deployed as a true dependency of our project

Best case scenario would have to have some SCSS or less files in this bundle, that contains all variables (such as colors)

**Comment by sylvainaerni** [comment]
Hello, 
FYI. This repository is not maintained anymore and handled by another team.
The new repository (https://github.com/swiss/designsystem) is now private.
Please contact <a href="mailto:Davy.Augier@bk.admin.ch">Davy.Augier@bk.admin.ch</a> to request an access.
